config/routes.rb
class OnlyAjaxRequest
  def matches?(request)
    request.xhr?
  end
end

Rails.application.routes.draw do
  resources :promocodes

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {:registrations => "users/registrations",:omniauth_callbacks => "users/omniauth_callbacks"}
  
  root 'home#index'

  get "events/delete_all", :constraints => OnlyAjaxRequest.new
  get "events/unparticipate", :constraints => OnlyAjaxRequest.new
  
  get "events/participate/:id"=>"events#participate", :constraints => OnlyAjaxRequest.new

  # get "messages/delete_all", :constraints => OnlyAjaxRequest.new
  # get "messages/restore", :constraints => OnlyAjaxRequest.new
  # post "messages/reply/:id"=>"messages#reply", :constraints => OnlyAjaxRequest.new
  get 'users/users_for_select', :constraints => OnlyAjaxRequest.new
  get 'profile/report_abuse', :constraints => OnlyAjaxRequest.new
  post 'subscribePromo'=>"users#subscribe_promocode",:constraints => OnlyAjaxRequest.new
  post 'users/requestFriend', :constraints => OnlyAjaxRequest.new
  post 'users/acceptFriend', :constraints => OnlyAjaxRequest.new
  post 'users/subscribe', :constraints => OnlyAjaxRequest.new
  post 'users/unsubscribe', :constraints => OnlyAjaxRequest.new
  get 'profile/viewed_me'
  post 'messages/contactUs', :constraints => OnlyAjaxRequest.new
  get 'users/invitations', :constraints => OnlyAjaxRequest.new
  post 'users/updatePassword', :constraints => OnlyAjaxRequest.new
  # post 'messages/sendMessage', :constraints => OnlyAjaxRequest.new

  resources :events, :constraints => OnlyAjaxRequest.new
  resources :saved_searches, :constraints => OnlyAjaxRequest.new

  resources :messages, :constraints => OnlyAjaxRequest.new
  resources :reply, :constraints => OnlyAjaxRequest.new
  resources :profile, :constraints => OnlyAjaxRequest.new
  resources :image, :constraints => OnlyAjaxRequest.new
  resources :search, :constraints => OnlyAjaxRequest.new
  resources :stripe, :constraints => OnlyAjaxRequest.new
  resources :static_pages, :constraints => OnlyAjaxRequest.new
  get "makeFavourite" =>  "profile#makeFavourite"

  get '*path', to: "home#index", format: :html

end

app/models/promocode.rb
class Promocode
  include Mongoid::Document
	include Mongoid::Timestamps
  field :validity, type: Integer
  field :is_active, type: Mongoid::Boolean
  field :code, type: String
  validates :code, uniqueness: true,presence: true
end

app/controllers/promocodes_controller.rb
class PromocodesController < ApplicationController
  before_action :set_promocode, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @promocodes = Promocode.all
    respond_with(@promocodes)
  end

  def show
    respond_with(@promocode)
  end

  def new
    @promocode = Promocode.new
    respond_with(@promocode)
  end

  def edit
  end

  def create
    @promocode = Promocode.new(promocode_params)
    @promocode.save
    respond_with(@promocode)
  end

  def update
    @promocode.update(promocode_params)
    respond_with(@promocode)
  end

  def destroy
    @promocode.destroy
    respond_with(@promocode)
  end

  private
    def set_promocode
      @promocode = Promocode.find(params[:id])
    end

    def promocode_params
      params.require(:promocode).permit(:validity, :active, :code)
    end
end

app/helpers/promocodes_helper.rb
module PromocodesHelper
end

app/views/promocodes/_form.html.erb
<%= form_for(@promocode) do |f| %>
  <% if @promocode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promocode.errors.count, "error") %> prohibited this promocode from being saved:</h2>

      <ul>
      <% @promocode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :validity %><br>
    <%= f.number_field :validity %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promocodes/edit.html.erb
<h1>Editing promocode</h1>

<%= render 'form' %>

<%= link_to 'Show', @promocode %> |
<%= link_to 'Back', promocodes_path %>

app/views/promocodes/index.html.erb
<h1>Listing promocodes</h1>

<table>
  <thead>
    <tr>
      <th>Validity</th>
      <th>Active</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promocodes.each do |promocode| %>
      <tr>
        <td><%= promocode.validity %></td>
        <td><%= promocode.active %></td>
        <td><%= promocode.code %></td>
        <td><%= link_to 'Show', promocode %></td>
        <td><%= link_to 'Edit', edit_promocode_path(promocode) %></td>
        <td><%= link_to 'Destroy', promocode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promocode', new_promocode_path %>

app/views/promocodes/new.html.erb
<h1>New promocode</h1>

<%= render 'form' %>

<%= link_to 'Back', promocodes_path %>

app/views/promocodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Validity:</strong>
  <%= @promocode.validity %>
</p>

<p>
  <strong>Active:</strong>
  <%= @promocode.active %>
</p>

<p>
  <strong>Code:</strong>
  <%= @promocode.code %>
</p>

<%= link_to 'Edit', edit_promocode_path(@promocode) %> |
<%= link_to 'Back', promocodes_path %>